name: "Build and Deploy"

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all commit history for accurate diff comparisons.

      # Step 2: Configure Pages for deployment
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      # Step 3: Setup Ruby environment with bundler cache enabled
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      # Step 4: Build the Jekyll site
      - name: Build site
        run: bundle exec jekyll build -d "_site"
        env:
          JEKYLL_ENV: "production"

      # Step 5: Test the generated site for broken links or issues
      - name: Test site
        run: |
          bundle exec htmlproofer _site \
